;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        coffee-dedent-line-backspace
        fill-paragraph
        kill-region
        sp--self-insert-command
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        find-file
        ibuffer
        ))
