;; This file is automatically generated by the multiple-cursors
;; extension.
;; It keeps track of your preferences for running commands with
;; multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        c-electric-lt-gt
        c-electric-slash
        coffee-dedent-line-backspace
        dabbrev-expand
        fill-paragraph
        kill-region
        sp--self-insert-command
        sp-remove-active-pair-overlay
        yas-expand
        ))

(setq mc/cmds-to-run-once
      '(
        find-file
        ibuffer
        ido-kill-buffer
        ))
